[ui]
agent_panel_sort = "spaces"

[terminal]
default_shell = "/home/linuxbrew/.linuxbrew/bin/zsh"
shell_mode = "login"
new_cwd = "follow"

[keys]
prefix = "ctrl+space"
previous_tab = ["prefix+p", "alt+shift+h"]
next_tab = ["prefix+n", "alt+shift+l"]
split_horizontal = 'prefix+"'
split_vertical = "prefix+%"
focus_pane_left = ["prefix+h", "prefix+left"]
focus_pane_down = ["prefix+j", "prefix+down"]
focus_pane_up = ["prefix+k", "prefix+up"]
focus_pane_right = ["prefix+l", "prefix+right"]
